cs50w/lecture3/hello/urls.py
from django.urls import path

from . import views
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.greetHtml, name = "greet"),
    path("brain", views.brain, name = "brain"),
]

cs50w/lecture3/lecture3/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls")),
]

cs50w/lecture3/newyear/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.isnewyear, name = "index"),
]

cs50w/lecture3/tasks/urls.py
from . import views
from django.urls import path

app_name = 'tasks'
urlpatterns = [
    path("", views.index, name = "index"),
    path("add", views.addtask, name = "add"),

]

cs50w/lecture3/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

def index(request):
    # print(request)
    return HttpResponse("Hello!")

def brain(request):
    return HttpResponse(f"Hello, Brain Obrain! {request}")

def greet(request, name):
    return HttpResponse(f"Hello, {name.capitalize()}!")
def greetHtml(request, name):
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    })

cs50w/lecture3/newyear/views.py
from django.shortcuts import render
import datetime

# Create your views here.

def isnewyear(request):
    now = datetime.datetime.now()
    return render(request,"newyear/index.html",{
        "newyear":now.month == 1 and now.day == 1
    })

cs50w/lecture3/tasks/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.




class NewTaskForm(forms.Form):
    task = forms.CharField(label = 'New Task:')

def index(request):
    if 'tasks' not in request.session:
        request.session['tasks'] = []
    return render(request, 'tasks/index.html',{
        'tasks': request.session['tasks']
    })

def addtask(request):
    if 'tasks' not in request.session:
        request.session['tasks'] = []

    if(request.method == 'POST'):
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data['task']
            request.session['tasks'] += [task]
            return HttpResponseRedirect(reverse('tasks:index'))
        else: return render(request, 'tasks/add.html',{
            'form':form
        })
    return render(request, 'tasks/add.html', {
        'form': NewTaskForm
    })

cs50w/lecture3/hello/templates/hello/greet.html
<!DOCTYPE html>
<html>
    <head>
        <title>Hello, {{name}}!</title>
    </head>
    <body>
        <h1>Hello, {{name}}!</h1>
    </body>
</html>

cs50w/lecture3/newyear/templates/newyear/index.html
{% load static%}
<!DOCTYPE html>
<html>
    <head>
        <title>Is new Year!</title>
        <link href="{% static 'newyear/style.css' %}" rel = "stylesheet">
    </head>
    <body>
        <h1>
            {%if newyear == True%}
                YES
            {%else%}
                NO
            {%endif%}
        </h1>
    </body>
</html>

cs50w/lecture3/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{%block body%}
<h1>Add task</h1>
<form action = "{%url 'tasks:add'%}" method = 'POST'>
    {%csrf_token%}
    {{form}}
    <input type = 'submit'>
</form>
<br>
<a href = '{% url 'tasks:index'%}'>View Task List </a>
{%endblock%}

cs50w/lecture3/tasks/templates/tasks/index.html
{% extends 'tasks/layout.html'%}
    {% block body%}
    <h1>Tasks</h1>
    <ul>
        {%for task in tasks%}
            <li>{{task}}</li>
            {%empty%}
            <li>No taks</li>
        {%endfor%}
    </ul>
 
    <a href = '{% url 'tasks:add' %}'>Add New Task</a>
    {% endblock %}  

cs50w/lecture3/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>Tasks</title>
    </head>
    <body>
       {% block body%}

       {%endblock%}
    </body>
    

</html>